version: "3.8"

services:
  dcgm-exporter:
    container_name: dcgm-exporter
    image: nvcr.io/nvidia/k8s/dcgm-exporter:2.1.4-2.3.1-ubuntu20.04
    restart: unless-stopped
    runtime: nvidia
    network_mode: host
    cap_add:
      - SYS_ADMIN
    entrypoint: ["dcgm-exporter"]
    command: ["-f", "/etc/dcgm-exporter/dcp-metrics-included.csv"]
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
