global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['192.168.50.173:9100']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['192.168.50.173:8080']
  - job_name: 'nvidia_smi'
    static_configs:
      - targets: ['192.168.50.173:9400']