version: "3.3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    volumes:
      - /mnt/data/loki:/loki
      - /opt/docker/loki/loki-config.yaml:/opt/docker/loki/loki-config.yaml:ro
    restart: unless-stopped
    ports:
      - "3100:3100"
    command: -config.file=/opt/docker/loki/loki-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /mnt/data/promtail:/var/log
      - /opt/docker/loki/loki-config.yaml:/etc/promtail/loki-config.yaml:ro
    restart: unless-stopped
    command: -config.file=/etc/promtail/loki-config.yaml
    networks:
      - loki
