---
- name: Install Docker tools
  hosts: remus
  become: yes

  roles:
    - role: docker
    - role: nginx-proxy
    - role: uptime-kuma
    - role: dcgm-exporter
    - role: prometheus
    - role: grafana
    - role: node-exporter
    - role: cAdvisor
    - role: loki
    - role: homepage
    - role: plex
      tags: plex